Occupation evaluation
nestauk/dap_prinz_green_jobs pull request #80
Opened 2023-10-11 13:34 UTC by lizgzil

---

# Description

Also includes the script of where I created the sample for the skills analysis!

Fixes #73 

# Instructions for Reviewer

In order to test the code in this PR you need to ...

Please pay special attention to ...

# Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ ] I have checked the code runs
- [ ] I have tested the code
- [ ] I have run `pre-commit` and addressed any issues not automatically fixed
- [ ] I have merged any new changes from `dev`
- [ ] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ ] I have explained this PR above
- [ ] I have requested a code review

2023-10-17 12:41 UTC, india-kerle requested changes
Looks great liz! Really great results. 

I haven't these scripts/notebooks, just reviewed - my only request for changes is for repo consistency to move the SOC evaluation sample file to `pipeline/evaluation` as opposed to where it currently is. 

I've also added some final evaluation ideas around comparing to an existing SOC mapper but that's a nice to have more than anything. Thanks!

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
> +"""
```suggestion
"""
Create a sample dataset to evaluate the skills extraction and mapping to green ESCO

python dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
"""
```

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +"""
I think this should be in the `evaluation/` directory for consistency as opposed to `green_measures/occupations/evaluation`

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
> +def format_skills_data(green_skills_outputs):
```suggestion
def format_skills_data(green_skills_outputs: Dict[str, dict]) -> pd.DataFrame:
```

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
> +
```suggestion
from typing import Dict
```

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
> +    )
save to s3 so people can access it? I saved the industries sample in an `industries` directory here: 's3://prinz-green-jobs/outputs/data/labelled_job_adverts/evaluation/'

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/evaluation/skills_evaluation_sample.py
> +    )
might want to save with the parameter `index=False` so you don't need to deal with an unnamed: 0 column

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +- 11% had poor quality SOC matches
😍

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +- 10% had poor quality SOC matches
😍😍😍

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +- 5% had good quality SOC matches
😍😍😍😍😍

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +We note that the results from the most commonly occuring job titles are probably better since the job title tends to be more clean and standardised.
true

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +# 🤔 Evaluation
I stumbled upon arthur turrell (director of ONS data science campus)'s github page and it looks like he has a `occupationcoder` repo that assigns a UK 3-digit standard occupational classification (SOC) code to the job. 

An extension of the evaluation could be comparing with existing approaches? i.e. aggregate up the soc6 codes

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +    random_job_titles = {k: v for (k, v) in random_job_titles}
would be good to set a seed for consistency

2023-10-17 12:41 UTC, india-kerle commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +    )
again, i think it would be nice if this was saved to s3

2023-11-07 10:02 UTC, lizgzil commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/README.md
> +# 🤔 Evaluation
Nice - I'll add it in, also the LM4A comparison (which I did a bit of during a previous iteration but havent repeated)

2023-11-07 10:08 UTC, lizgzil commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +    random_job_titles = {k: v for (k, v) in random_job_titles}
oh god - that's bad I didn't, thanks for picking up! I have added one, but I guess it's kind of too late

2023-11-07 10:10 UTC, lizgzil commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +    )
good point

2023-11-07 10:12 UTC, lizgzil commented on dap_prinz_green_jobs/pipeline/green_measures/occupations/evaluation/socmapper_evaluation_sample.py
> +"""
will do!

2023-11-07 10:19 UTC, lizgzil commented
Thanks @india-kerle - I've addressed your comments.

I think when we have merged all evaluation stuff we can create a better structure for this folder - e.g. at the moment the occupation evaluation samples are in one place, with the evaluation notebook and README in another.

2023-11-07 10:19 UTC, merged